// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5qqynfEyE1GRjXiSU2SzXg
// Component: HtSj_bf-pk
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_focus_doc_test.module.css"; // plasmic-import: 5qqynfEyE1GRjXiSU2SzXg/projectcss
import sty from "./PlasmicTokenDocumentation.module.css"; // plasmic-import: HtSj_bf-pk/css

export type PlasmicTokenDocumentation__VariantMembers = {};
export type PlasmicTokenDocumentation__VariantsArgs = {};
type VariantPropType = keyof PlasmicTokenDocumentation__VariantsArgs;
export const PlasmicTokenDocumentation__VariantProps =
  new Array<VariantPropType>();

export type PlasmicTokenDocumentation__ArgsType = {};
type ArgPropType = keyof PlasmicTokenDocumentation__ArgsType;
export const PlasmicTokenDocumentation__ArgProps = new Array<ArgPropType>();

export type PlasmicTokenDocumentation__OverridesType = {
  root?: p.Flex<"div">;
  tokenName?: p.Flex<"div">;
  textValue?: p.Flex<"div">;
  description?: p.Flex<"div">;
};

export interface DefaultTokenDocumentationProps {
  className?: string;
}

function PlasmicTokenDocumentation__RenderFunc(props: {
  variants: PlasmicTokenDocumentation__VariantsArgs;
  args: PlasmicTokenDocumentation__ArgsType;
  overrides: PlasmicTokenDocumentation__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  return (
    true ? (
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(
          projectcss.all,
          projectcss.root_reset,
          projectcss.plasmic_default_styles,
          projectcss.plasmic_mixins,
          sty.root
        )}
      >
        <div
          data-plasmic-name={"tokenName"}
          data-plasmic-override={overrides.tokenName}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.tokenName
          )}
        >
          {"tokenName"}
        </div>

        <div
          data-plasmic-name={"textValue"}
          data-plasmic-override={overrides.textValue}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.textValue
          )}
        >
          {"value"}
        </div>

        <div
          data-plasmic-name={"description"}
          data-plasmic-override={overrides.description}
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.description
          )}
        >
          {"description"}
        </div>
      </div>
    ) : null
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "tokenName", "textValue", "description"],
  tokenName: ["tokenName"],
  textValue: ["textValue"],
  description: ["description"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  tokenName: "div";
  textValue: "div";
  description: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTokenDocumentation__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTokenDocumentation__VariantsArgs;
    args?: PlasmicTokenDocumentation__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTokenDocumentation__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTokenDocumentation__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTokenDocumentation__ArgProps,
          internalVariantPropNames: PlasmicTokenDocumentation__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicTokenDocumentation__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTokenDocumentation";
  } else {
    func.displayName = `PlasmicTokenDocumentation.${nodeName}`;
  }
  return func;
}

export const PlasmicTokenDocumentation = Object.assign(
  // Top-level PlasmicTokenDocumentation renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    tokenName: makeNodeComponent("tokenName"),
    textValue: makeNodeComponent("textValue"),
    description: makeNodeComponent("description"),

    // Metadata about props expected for PlasmicTokenDocumentation
    internalVariantProps: PlasmicTokenDocumentation__VariantProps,
    internalArgProps: PlasmicTokenDocumentation__ArgProps
  }
);

export default PlasmicTokenDocumentation;
/* prettier-ignore-end */
