// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 3zhG9z8RSkaFG4kUrEQkA
// Component: -CIawKX8tr
import * as React from "react";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: 3zhG9z8RSkaFG4kUrEQkA/projectcss
import sty from "./PlasmicTokenTemplate.module.css"; // plasmic-import: -CIawKX8tr/css

export const PlasmicTokenTemplate__VariantProps = new Array();

export const PlasmicTokenTemplate__ArgProps = new Array();

function PlasmicTokenTemplate__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__qt9Sz
        )}
      >
        {"wdqwdqwdqwdq"}
      </div>

      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__pNgT
        )}
      >
        {"123"}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTokenTemplate__ArgProps,
          internalVariantPropNames: PlasmicTokenTemplate__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicTokenTemplate__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTokenTemplate";
  } else {
    func.displayName = `PlasmicTokenTemplate.${nodeName}`;
  }
  return func;
}

export const PlasmicTokenTemplate = Object.assign(
  // Top-level PlasmicTokenTemplate renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTokenTemplate
    internalVariantProps: PlasmicTokenTemplate__VariantProps,
    internalArgProps: PlasmicTokenTemplate__ArgProps
  }
);

export default PlasmicTokenTemplate;
/* prettier-ignore-end */
