// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: b6nKE7i8gN5v6BLYoUcJjc
// Component: NAQSAztB7WS2W4
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Nav from "../../Nav"; // plasmic-import: 29bXtXSfKv4wef/component
import SubNav from "../../SubNav"; // plasmic-import: Pyz-ejhh9PT-70/component
import Button2 from "../../Button2"; // plasmic-import: gqYGTpy-VKih-k/component
import { Heading } from "@chakra-ui/react"; // plasmic-import: LUZ-EadiFt-pKZ/codeComponent
import { Text } from "@chakra-ui/react"; // plasmic-import: v15y1zx5wjOie1/codeComponent
import { Button } from "@chakra-ui/react"; // plasmic-import: 1zjFflbhvmK0o/codeComponent
import { CheckCircleIcon } from "@chakra-ui/react"; // plasmic-import: GSuP1QQXRL2iP/codeComponent
import { Tabs } from "@chakra-ui/react"; // plasmic-import: jM-c9S8dG8S0c4/codeComponent
import { TabList } from "@chakra-ui/react"; // plasmic-import: FXQF_HUkAEK9Dn/codeComponent
import { Tab } from "@chakra-ui/react"; // plasmic-import: _ZE645AF17I4h0/codeComponent
import { TabPanels } from "@chakra-ui/react"; // plasmic-import: AB2xSLDEjMl_Kp/codeComponent
import { TabPanel } from "@chakra-ui/react"; // plasmic-import: r6nlMZjR1r4zub/codeComponent
import { ButtonPreview } from "../../../styles/ButtonPreview"; // plasmic-import: PcwhN-FHyr0-AH/codeComponent
import { ChakraDocs } from "../../../styles/ChakraDocs"; // plasmic-import: wtErYCFh5X4hT/codeComponent

import { useScreenVariants as useScreenVariantssqj7Gi5LUgTnD } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: SQJ7GI5lUG-TnD/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_focus_poc_local_host.module.css"; // plasmic-import: b6nKE7i8gN5v6BLYoUcJjc/projectcss
import sty from "./PlasmicHeading.module.css"; // plasmic-import: NAQSAztB7WS2W4/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: CHjFDXi0wrulJy/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: N2O1cciiO0c85w/icon

export type PlasmicHeading__VariantMembers = {
  props: "props";
  theming: "theming";
};
export type PlasmicHeading__VariantsArgs = {
  props?: SingleBooleanChoiceArg<"props">;
  theming?: SingleBooleanChoiceArg<"theming">;
};
type VariantPropType = keyof PlasmicHeading__VariantsArgs;
export const PlasmicHeading__VariantProps = new Array<VariantPropType>(
  "props",
  "theming"
);

export type PlasmicHeading__ArgsType = {};
type ArgPropType = keyof PlasmicHeading__ArgsType;
export const PlasmicHeading__ArgProps = new Array<ArgPropType>();

export type PlasmicHeading__OverridesType = {
  root?: p.Flex<"div">;
  nav?: p.Flex<typeof Nav>;
  subNav?: p.Flex<typeof SubNav>;
  button2?: p.Flex<typeof Button2>;
  tabs?: p.Flex<typeof Tabs>;
  tabList?: p.Flex<typeof TabList>;
  tabPanels?: p.Flex<typeof TabPanels>;
  buttonPreview?: p.Flex<typeof ButtonPreview>;
  chakraDocs?: p.Flex<typeof ChakraDocs>;
};

export interface DefaultHeadingProps {}

function PlasmicHeading__RenderFunc(props: {
  variants: PlasmicHeading__VariantsArgs;
  args: PlasmicHeading__ArgsType;
  overrides: PlasmicHeading__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const stateSpecs = React.useMemo(
    () => [
      {
        path: "props",
        type: "private",
        initFunc: ($props, $state, $ctx) => $props.props
      },
      {
        path: "theming",
        type: "private",
        initFunc: ($props, $state, $ctx) => $props.theming
      }
    ],
    [$props, $ctx]
  );
  const $state = p.useDollarState(stateSpecs, $props, $ctx);

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantssqj7Gi5LUgTnD()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root,
            {
              [sty.rootprops]: hasVariant($state, "props", "props"),
              [sty.roottheming]: hasVariant($state, "theming", "theming")
            }
          )}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__n3Wkm)}
          >
            <Nav
              data-plasmic-name={"nav"}
              data-plasmic-override={overrides.nav}
              className={classNames("__wab_instance", sty.nav)}
            />

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___0L6Xs, {
                [sty.freeBoxprops___0L6Xshn0U5]: hasVariant(
                  $state,
                  "props",
                  "props"
                )
              })}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__kk2XI)}
              >
                <SubNav
                  data-plasmic-name={"subNav"}
                  data-plasmic-override={overrides.subNav}
                  className={classNames("__wab_instance", sty.subNav)}
                />

                {false ? (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__d64Pf)}
                  >
                    <button
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        projectcss.__wab_text,
                        sty.button__aiFq9
                      )}
                    >
                      {"Sign up"}
                    </button>

                    {true ? (
                      <Button2
                        data-plasmic-name={"button2"}
                        data-plasmic-override={overrides.button2}
                        className={classNames("__wab_instance", sty.button2)}
                        color={"clear" as const}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__y4GdJ
                            )}
                            role={"img"}
                          />
                        }
                        startIcon={
                          <ChecksvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___1RjHk
                            )}
                            role={"img"}
                          />
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__mj4
                          )}
                        >
                          {"Log in"}
                        </div>
                      </Button2>
                    ) : null}
                  </div>
                ) : null}
              </p.Stack>

              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__dfUu)}
                >
                  <Heading
                    className={classNames("__wab_instance", sty.heading__qxKCx)}
                    noOfLines={1 as const}
                    size={"xl" as const}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jmo9C
                      )}
                    >
                      {"Heading"}
                    </div>
                  </Heading>

                  <Text
                    align={"left" as const}
                    casing={"capitalise" as const}
                    className={classNames("__wab_instance", sty.text__jYmEs, {
                      [sty.textprops__jYmEshn0U5]: hasVariant(
                        $state,
                        "props",
                        "props"
                      )
                    })}
                    decoration={"none" as const}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hlq9Y,
                        {
                          [sty.textprops__hlq9YHn0U5]: hasVariant(
                            $state,
                            "props",
                            "props"
                          ),
                          [sty.texttheming__hlq9YxizSj]: hasVariant(
                            $state,
                            "theming",
                            "theming"
                          )
                        }
                      )}
                    >
                      {
                        "Heading is used to render semantic HTML heading elements."
                      }
                    </div>
                  </Text>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__vzgPm)}
                  >
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__zTeJc
                      )}
                      colorScheme={"gray" as const}
                      isActive={true}
                      leftIcon={
                        <CheckCircleIcon
                          className={classNames(
                            "__wab_instance",
                            sty.checkCircleIcon__ndTnE
                          )}
                        />
                      }
                      rightIcon={null}
                      size={"xs" as const}
                      variant={"outline" as const}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___18Or2
                        )}
                      >
                        {"Code"}
                      </div>
                    </Button>

                    <Button
                      className={classNames("__wab_instance", sty.button__dPuI)}
                      colorScheme={"gray" as const}
                      isActive={true}
                      leftIcon={
                        <CheckCircleIcon
                          className={classNames(
                            "__wab_instance",
                            sty.checkCircleIcon___2Su1U
                          )}
                        />
                      }
                      rightIcon={null}
                      size={"xs" as const}
                      variant={"outline" as const}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___5Y581
                        )}
                      >
                        {"Design"}
                      </div>
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__uFkI0
                      )}
                      colorScheme={"gray" as const}
                      isActive={true}
                      leftIcon={
                        <CheckCircleIcon
                          className={classNames(
                            "__wab_instance",
                            sty.checkCircleIcon__w31F2
                          )}
                        />
                      }
                      rightIcon={null}
                      size={"xs" as const}
                      variant={"outline" as const}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rjHrr
                        )}
                      >
                        {"Business"}
                      </div>
                    </Button>
                  </p.Stack>

                  <Tabs
                    data-plasmic-name={"tabs"}
                    data-plasmic-override={overrides.tabs}
                    className={classNames("__wab_instance", sty.tabs, {
                      [sty.tabsprops]: hasVariant($state, "props", "props"),
                      [sty.tabstheming]: hasVariant(
                        $state,
                        "theming",
                        "theming"
                      )
                    })}
                    variant={"soft-rounded" as const}
                  >
                    <TabList
                      data-plasmic-name={"tabList"}
                      data-plasmic-override={overrides.tabList}
                      className={classNames("__wab_instance", sty.tabList, {
                        [sty.tabListprops]: hasVariant(
                          $state,
                          "props",
                          "props"
                        ),
                        [sty.tabListtheming]: hasVariant(
                          $state,
                          "theming",
                          "theming"
                        )
                      })}
                    >
                      <Tab
                        className={classNames(
                          "__wab_instance",
                          sty.tab__xgXmA,
                          {
                            [sty.tabtheming__xgXmAxizSj]: hasVariant(
                              $state,
                              "theming",
                              "theming"
                            )
                          }
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__exyf
                          )}
                        >
                          {"Usage"}
                        </div>
                      </Tab>

                      <Tab
                        className={classNames("__wab_instance", sty.tab__k10Gj)}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__egsJp
                          )}
                        >
                          {"Props"}
                        </div>
                      </Tab>

                      <Tab
                        className={classNames("__wab_instance", sty.tab__xTzf, {
                          [sty.tabprops__xTzfhn0U5]: hasVariant(
                            $state,
                            "props",
                            "props"
                          ),
                          [sty.tabtheming__xTzFxizSj]: hasVariant(
                            $state,
                            "theming",
                            "theming"
                          )
                        })}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__f8SnO
                          )}
                        >
                          {"Theming"}
                        </div>
                      </Tab>
                    </TabList>

                    <TabPanels
                      data-plasmic-name={"tabPanels"}
                      data-plasmic-override={overrides.tabPanels}
                      className={classNames("__wab_instance", sty.tabPanels)}
                    >
                      <TabPanel
                        className={classNames(
                          "__wab_instance",
                          sty.tabPanel__izAIl
                        )}
                      >
                        <Heading
                          className={classNames(
                            "__wab_instance",
                            sty.heading___9R9I
                          )}
                          noOfLines={1 as const}
                          size={"md" as const}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__l18MM
                            )}
                          >
                            {"Changing visual size"}
                          </div>
                        </Heading>

                        <Text
                          align={"left" as const}
                          casing={"capitalise" as const}
                          className={classNames(
                            "__wab_instance",
                            sty.text__lnOey,
                            {
                              [sty.textprops__lnOeyHn0U5]: hasVariant(
                                $state,
                                "props",
                                "props"
                              )
                            }
                          )}
                          decoration={"none" as const}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rMoAe,
                              {
                                [sty.textprops__rMoAeHn0U5]: hasVariant(
                                  $state,
                                  "props",
                                  "props"
                                ),
                                [sty.texttheming__rMoAexizSj]: hasVariant(
                                  $state,
                                  "theming",
                                  "theming"
                                )
                              }
                            )}
                          >
                            {
                              "To increase the visual size of the heading, use the size props. This property ensures that the heading size automatically adjusts for smaller screens."
                            }
                          </div>
                        </Text>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__cWqIs
                          )}
                        >
                          <Heading
                            className={classNames(
                              "__wab_instance",
                              sty.heading__om1Ft
                            )}
                            noOfLines={1 as const}
                            size={"4xl" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__zHkqy
                              )}
                            >
                              {"(4xl) In love with React & Next"}
                            </div>
                          </Heading>

                          <Heading
                            className={classNames(
                              "__wab_instance",
                              sty.heading__qGwvT
                            )}
                            noOfLines={1 as const}
                            size={"3xl" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__u5XOl
                              )}
                            >
                              {"(3xl) In love with React"}
                            </div>
                          </Heading>

                          <Heading
                            className={classNames(
                              "__wab_instance",
                              sty.heading___7YlYg
                            )}
                            noOfLines={1 as const}
                            size={"2xl" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text___74NB5
                              )}
                            >
                              {"(2xl) In love with React & Next"}
                            </div>
                          </Heading>

                          <Heading
                            className={classNames(
                              "__wab_instance",
                              sty.heading__md71J
                            )}
                            noOfLines={1 as const}
                            size={"xl" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__qAvam
                              )}
                            >
                              {"(xl) In love with React & Next"}
                            </div>
                          </Heading>

                          <Heading
                            className={classNames(
                              "__wab_instance",
                              sty.heading__uotWo
                            )}
                            noOfLines={1 as const}
                            size={"lg" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gqcCv
                              )}
                            >
                              {"(lg) In love with React & Next"}
                            </div>
                          </Heading>

                          <Heading
                            className={classNames(
                              "__wab_instance",
                              sty.heading__vkRni
                            )}
                            noOfLines={1 as const}
                            size={"md" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__dPsjr
                              )}
                            >
                              {"(md) In love with React & Next"}
                            </div>
                          </Heading>

                          <Heading
                            className={classNames(
                              "__wab_instance",
                              sty.heading___1AcgF
                            )}
                            noOfLines={1 as const}
                            size={"sm" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__dfshK
                              )}
                            >
                              {"(sm) In love with React & Next"}
                            </div>
                          </Heading>

                          <Heading
                            className={classNames(
                              "__wab_instance",
                              sty.heading__xKjC
                            )}
                            noOfLines={1 as const}
                            size={"xs" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__bo1WV
                              )}
                            >
                              {"(xm) In love with React & Next"}
                            </div>
                          </Heading>
                        </p.Stack>

                        <Heading
                          className={classNames(
                            "__wab_instance",
                            sty.heading__geplP
                          )}
                          noOfLines={1 as const}
                          size={"md" as const}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__kDpj0
                            )}
                          >
                            {"Truncate heading"}
                          </div>
                        </Heading>

                        <Text
                          align={"left" as const}
                          casing={"capitalise" as const}
                          className={classNames(
                            "__wab_instance",
                            sty.text__uHqvy,
                            {
                              [sty.textprops__uHqvyHn0U5]: hasVariant(
                                $state,
                                "props",
                                "props"
                              )
                            }
                          )}
                          decoration={"none" as const}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__c0Qyv,
                              {
                                [sty.textprops__c0Qyvhn0U5]: hasVariant(
                                  $state,
                                  "props",
                                  "props"
                                ),
                                [sty.texttheming__c0QyVxizSj]: hasVariant(
                                  $state,
                                  "theming",
                                  "theming"
                                )
                              }
                            )}
                          >
                            {
                              "If you'd like to truncate the heading after a specific number of lines, pass the noOfLines prop. This will render an ellipsis when the heading exceeds the width of the viewport or maxWidth prop."
                            }
                          </div>
                        </Text>

                        <Heading
                          className={classNames(
                            "__wab_instance",
                            sty.heading__ubaXd
                          )}
                          noOfLines={1 as const}
                          size={"2xl" as const}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___33Kjv
                            )}
                          >
                            {"Basic text writing, including headings,"}
                          </div>
                        </Heading>

                        <Heading
                          className={classNames(
                            "__wab_instance",
                            sty.heading__xim5B
                          )}
                          noOfLines={1 as const}
                          size={"md" as const}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gqnth
                            )}
                          >
                            {"Composition"}
                          </div>
                        </Heading>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__kiJ1
                          )}
                        >
                          <Heading
                            className={classNames(
                              "__wab_instance",
                              sty.heading___49Xsy
                            )}
                            noOfLines={2 as const}
                            size={"2xl" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__lKL
                              )}
                            >
                              {"Modern online and offline payments for Africa"}
                            </div>
                          </Heading>

                          <Text
                            align={"left" as const}
                            casing={"capitalise" as const}
                            className={classNames(
                              "__wab_instance",
                              sty.text__clxcv,
                              {
                                [sty.textprops__clxcvHn0U5]: hasVariant(
                                  $state,
                                  "props",
                                  "props"
                                )
                              }
                            )}
                            decoration={"none" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__lvu3H,
                                {
                                  [sty.textprops__lvu3HHn0U5]: hasVariant(
                                    $state,
                                    "props",
                                    "props"
                                  ),
                                  [sty.texttheming__lvu3HxizSj]: hasVariant(
                                    $state,
                                    "theming",
                                    "theming"
                                  )
                                }
                              )}
                            >
                              {
                                "Paystack helps businesses in Africa get paid by anyone, anywhere in the world"
                              }
                            </div>
                          </Text>

                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__mKk0T
                            )}
                            colorScheme={"green" as const}
                            isActive={true}
                            leftIcon={null}
                            rightIcon={null}
                            size={"lg" as const}
                            variant={"solid" as const}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__yJBs
                              )}
                            >
                              {"Create a free account"}
                            </div>
                          </Button>
                        </p.Stack>
                      </TabPanel>

                      <TabPanel
                        className={classNames(
                          "__wab_instance",
                          sty.tabPanel__w6T8T,
                          {
                            [sty.tabPanelprops__w6T8Thn0U5]: hasVariant(
                              $state,
                              "props",
                              "props"
                            )
                          }
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__iFeT9,
                            {
                              [sty.textprops__iFeT9Hn0U5]: hasVariant(
                                $state,
                                "props",
                                "props"
                              )
                            }
                          )}
                        >
                          {hasVariant($state, "props", "props")
                            ? "Tab 2's Panel Content"
                            : "Tab 2's Panel Content"}
                        </div>

                        {(
                          hasVariant($state, "props", "props") ? true : true
                        ) ? (
                          <ButtonPreview
                            data-plasmic-name={"buttonPreview"}
                            data-plasmic-override={overrides.buttonPreview}
                            className={classNames(
                              "__wab_instance",
                              sty.buttonPreview,
                              {
                                [sty.buttonPreviewprops]: hasVariant(
                                  $state,
                                  "props",
                                  "props"
                                )
                              }
                            )}
                          />
                        ) : null}
                      </TabPanel>

                      <TabPanel
                        className={classNames(
                          "__wab_instance",
                          sty.tabPanel__ttBp1
                        )}
                      >
                        <ChakraDocs
                          data-plasmic-name={"chakraDocs"}
                          data-plasmic-override={overrides.chakraDocs}
                          className={classNames(
                            "__wab_instance",
                            sty.chakraDocs,
                            {
                              [sty.chakraDocstheming]: hasVariant(
                                $state,
                                "theming",
                                "theming"
                              )
                            }
                          )}
                          path={
                            hasVariant($state, "theming", "theming")
                              ? ("btn.negative" as const)
                              : ("btn.primary" as const)
                          }
                          set={"core/color" as const}
                          theme={
                            hasVariant($state, "theming", "theming")
                              ? ("dark" as const)
                              : ("dark" as const)
                          }
                        />

                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__yDiab,
                            {
                              [sty.texttheming__yDiaBxizSj]: hasVariant(
                                $state,
                                "theming",
                                "theming"
                              )
                            }
                          )}
                        >
                          {hasVariant($state, "theming", "theming")
                            ? "Design Tokens..."
                            : "Tab 3's Panel Content"}
                        </div>
                      </TabPanel>
                    </TabPanels>
                  </Tabs>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__jK2O7
                    )}
                  >
                    {
                      "Chakra  is used for both Design and Development\nDeveloper docs visit:  https://chakra-ui.com/docs/components/button \nDesign file visit: [FigmaLink to Button] \n"
                    }
                  </div>
                </p.Stack>
              ) : null}
            </p.Stack>
          </p.Stack>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "nav",
    "subNav",
    "button2",
    "tabs",
    "tabList",
    "tabPanels",
    "buttonPreview",
    "chakraDocs"
  ],
  nav: ["nav"],
  subNav: ["subNav"],
  button2: ["button2"],
  tabs: ["tabs", "tabList", "tabPanels", "buttonPreview", "chakraDocs"],
  tabList: ["tabList"],
  tabPanels: ["tabPanels", "buttonPreview", "chakraDocs"],
  buttonPreview: ["buttonPreview"],
  chakraDocs: ["chakraDocs"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  nav: typeof Nav;
  subNav: typeof SubNav;
  button2: typeof Button2;
  tabs: typeof Tabs;
  tabList: typeof TabList;
  tabPanels: typeof TabPanels;
  buttonPreview: typeof ButtonPreview;
  chakraDocs: typeof ChakraDocs;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeading__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeading__VariantsArgs;
    args?: PlasmicHeading__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHeading__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHeading__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHeading__ArgProps,
          internalVariantPropNames: PlasmicHeading__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicHeading__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeading";
  } else {
    func.displayName = `PlasmicHeading.${nodeName}`;
  }
  return func;
}

export const PlasmicHeading = Object.assign(
  // Top-level PlasmicHeading renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    nav: makeNodeComponent("nav"),
    subNav: makeNodeComponent("subNav"),
    button2: makeNodeComponent("button2"),
    tabs: makeNodeComponent("tabs"),
    tabList: makeNodeComponent("tabList"),
    tabPanels: makeNodeComponent("tabPanels"),
    buttonPreview: makeNodeComponent("buttonPreview"),
    chakraDocs: makeNodeComponent("chakraDocs"),

    // Metadata about props expected for PlasmicHeading
    internalVariantProps: PlasmicHeading__VariantProps,
    internalArgProps: PlasmicHeading__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHeading;
/* prettier-ignore-end */
