// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: b6nKE7i8gN5v6BLYoUcJjc
// Component: _pwyTS5F_oeX4v
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { AspectRatio } from "@chakra-ui/react"; // plasmic-import: MCUKmpbC_6wd9/codeComponent
import { Image } from "@chakra-ui/react"; // plasmic-import: N1-RiKhCicwgJ/codeComponent
import SubNav from "../../SubNav"; // plasmic-import: Pyz-ejhh9PT-70/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_focus_poc_local_host.module.css"; // plasmic-import: b6nKE7i8gN5v6BLYoUcJjc/projectcss
import sty from "./PlasmicImage.module.css"; // plasmic-import: _pwyTS5F_oeX4v/css

export type PlasmicImage__VariantMembers = {};
export type PlasmicImage__VariantsArgs = {};
type VariantPropType = keyof PlasmicImage__VariantsArgs;
export const PlasmicImage__VariantProps = new Array<VariantPropType>();

export type PlasmicImage__ArgsType = {};
type ArgPropType = keyof PlasmicImage__ArgsType;
export const PlasmicImage__ArgProps = new Array<ArgPropType>();

export type PlasmicImage__OverridesType = {
  root?: p.Flex<"div">;
  aspectRatio?: p.Flex<typeof AspectRatio>;
  subNav?: p.Flex<typeof SubNav>;
};

export interface DefaultImageProps {}

function PlasmicImage__RenderFunc(props: {
  variants: PlasmicImage__VariantsArgs;
  args: PlasmicImage__ArgsType;
  overrides: PlasmicImage__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            sty.root
          )}
        >
          <AspectRatio
            data-plasmic-name={"aspectRatio"}
            data-plasmic-override={overrides.aspectRatio}
            className={classNames("__wab_instance", sty.aspectRatio)}
            ratio={1.77 as const}
          >
            <Image
              className={classNames("__wab_instance", sty.image__t0Qdm)}
              fallbackSrc={"https://via.placeholder.com/150" as const}
              src={"https://bit.ly/naruto-sage" as const}
            />
          </AspectRatio>

          <SubNav
            data-plasmic-name={"subNav"}
            data-plasmic-override={overrides.subNav}
            className={classNames("__wab_instance", sty.subNav)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "aspectRatio", "subNav"],
  aspectRatio: ["aspectRatio"],
  subNav: ["subNav"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  aspectRatio: typeof AspectRatio;
  subNav: typeof SubNav;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicImage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicImage__VariantsArgs;
    args?: PlasmicImage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicImage__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicImage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicImage__ArgProps,
          internalVariantPropNames: PlasmicImage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicImage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicImage";
  } else {
    func.displayName = `PlasmicImage.${nodeName}`;
  }
  return func;
}

export const PlasmicImage = Object.assign(
  // Top-level PlasmicImage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    aspectRatio: makeNodeComponent("aspectRatio"),
    subNav: makeNodeComponent("subNav"),

    // Metadata about props expected for PlasmicImage
    internalVariantProps: PlasmicImage__VariantProps,
    internalArgProps: PlasmicImage__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicImage;
/* prettier-ignore-end */
