// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5qqynfEyE1GRjXiSU2SzXg
// Component: HtSj_bf-pk
import * as React from "react";
import * as ph from "@plasmicapp/host";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_focus_doc_test.module.css"; // plasmic-import: 5qqynfEyE1GRjXiSU2SzXg/projectcss
import sty from "./PlasmicTokenDocumentation.module.css"; // plasmic-import: HtSj_bf-pk/css

export const PlasmicTokenDocumentation__VariantProps = new Array();

export const PlasmicTokenDocumentation__ArgProps = new Array();

function PlasmicTokenDocumentation__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  return (
    <div
      data-plasmic-name={"name"}
      data-plasmic-override={overrides.name}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.__wab_text,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.name
      )}
    >
      {"value "}
    </div>
  );
}

const PlasmicDescendants = {
  name: ["name"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicTokenDocumentation__ArgProps,
          internalVariantPropNames: PlasmicTokenDocumentation__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicTokenDocumentation__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "name") {
    func.displayName = "PlasmicTokenDocumentation";
  } else {
    func.displayName = `PlasmicTokenDocumentation.${nodeName}`;
  }
  return func;
}

export const PlasmicTokenDocumentation = Object.assign(
  // Top-level PlasmicTokenDocumentation renders the root element
  makeNodeComponent("name"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTokenDocumentation
    internalVariantProps: PlasmicTokenDocumentation__VariantProps,
    internalArgProps: PlasmicTokenDocumentation__ArgProps
  }
);

export default PlasmicTokenDocumentation;
/* prettier-ignore-end */
